spring:
  application:
    name: device-simulator

server:
  port: 23456
  tomcat:
    threads:
      max: 100
  servlet:
    session:
      timeout: 600 #设置会话超时时间,单位是秒

send:
  url: http://iot.nomelin.top/api/connect/uploadData